### PR TITLE
Random gen integration

### PR DESCRIPTION
**Pull request by aZina0**
Adds player to the random gen world
Adds ability to assign player and exit spawn points in each room
Changes directions inside `LevelGeneration.cs` from `1, 2, 3, 4, 5` to `L, R, D`

### CODE REVIEW

**Comment by nbakotic** [comment]
Running into a wall launches the player outside of the map for some reason

**Comment by aZina0** [comment]
> Running into a wall launches the player outside of the map for some reason

Yeah I am not sure why it does that. An issue (#37) related to this was already created.

**Comment by AKStifter** [comment]
There appears to be an invisible object in the center of some rooms.

**Comment by aZina0** [comment]
Each room has a object in the middle with a collider in it. It is a bit odd and I assume this is used in SpawnRoom.cs to check for existence of nearby rooms.

**Comment by AKStifter** [comment]
Is it possible to make the object smaller or simply remove collision with the object?

**Comment by aZina0** [comment]
Yeah we remove that system and replace with something else, or disable collisions with the player. If we go with the second option we are going to also have to remove collision with bullets/weapons/enemies etc.

**Pull request merged**
